services:
  hospital-dashboard:
    build: .
    container_name: hospital_dashboard
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    command: streamlit run dashboard/app.py --server.address=0.0.0.0

  hospital-api:
    build: .
    container_name: hospital_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000